wandb: # Empty because of sanitation
  key:
  entity:
  project:


set: val
multiprocessing: True
cpu_count: 64
random_seed: 4

debug: False

save_models: False # Saves debug models

data:
  name: "OOD"
  path: # ./data/models
  splits: # ./data/s Path to folder where train.txt, val.txt, test.txt are located for splitting dataset into sets
  save: "./generated"
  turn_on_save: True

noise:
  is_on: True
  amp: 0.06
  freq: 2.8

gen:
  resolution: 64
  size: [0.10,0.60]
  shift_mag: 0.66
  max_num_holes: 3

  bool_method: sdf
  context_type: relative
  bbox_scale: 2.0
  treatment: ["final"] # final, ori | only in OOD

antag:
  antagonist: False
  method: separate # together, separate
